### ISSUE TITLE
button .squished not reliable

### ISSUE THREAD

**Issue by BenCavens** [thinktomorrow/warpaint#10]
button with class `.squished` shows unreliable padding. This is because it depends on the font relation.
A button with less text will have a different effect if it would have a large amount of text inside of it.

Need to inspect this a bit further

**Comment by kingjohnny** [comment]
ik zie niet echt een probleem...
![image](https://user-images.githubusercontent.com/4115846/30827834-c3455882-a23b-11e7-8f6a-6d0a06931236.png)

**Comment by BenCavens** [comment]
Btn issue is opgelost. Inconsistentie kwam van een vorige versie 0.0.4
