### ISSUE TITLE
column responsiveness column-6 l-column?

### ISSUE THREAD

**Issue by alberttomasiak** [thinktomorrow/warpaint#11]
I have 4 divs in this particular situation. They're displayed 2x2 on mobile/tablet and on desktop they show up 4 in a row. This has a drawback though, since it isn't prepared for a fifth div. Changing `l-column-3` to `l-column` will give priority to `column-6`.

> `<div class="banner__services-single first-service column-6 l-column-3">
            <div class="banner__top-wrap centered">
                <div class="banner__top-img centered first--image"></div>
                <h2>lorem ipsum</h2>
            </div>
            <div class="banner__bottom-wrap">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
        </div>`

**Comment by BenCavens** [comment]
this is now fixed and l-column rule will get priority as soon as large breakpoint is reached.
